### PR TITLE
fix null reference issues

### PR DESCRIPTION
**Pull request by CooperLiu**
check unprotected data is null or not before deserialize it.

### CODE REVIEW

**Review by dmarlow — APPROVED** [review]

**Comment by dmarlow** [comment]
NuGet package updated as version 1.4.1 with these changes

**Comment by akrock** [comment]
@CooperLiu why did you delete `AspNet4TicketDataFormat`?

This was a public interface into this package that had a purpose. Also you have now released a build version update with a breaking interface change because this file was deleted.

**Comment by dmarlow** [comment]
I'll get it back up. My apologies, I should have looked more closely. I haven't looked at this code for quite some time.

**Comment by dmarlow** [comment]
Fixed in version 1.5.0

**Comment by akrock** [comment]
Thanks, I just happened to notice the PR in my email. We would have noticed it next time we tried to bump the version 😄

**Pull request merged**
